---
title: "Reading Notes: 'Specialization and Trade'"
description: |
  Tags: Arnold Kling, Political Economy
author:
  - name: Casey Caprini
date: 02-09-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Book Info
["Specialization and Trade: A Re-introduction to Economics"](https://www.amazon.com/Specialization-Trade-Arnold-Kling/dp/1944424156/)

by Arnold Kling

### Thesis  

The economy is best viewed as a set of patterns of sustainable specialization and trade (PSST).  

Specialization should replace scarcity and choice as the most fundamental aspect of economics.  

> “The work you do probably does not produce something you could consume. Even more striking is the fact that almost everything you consume is something you could not produce.”  

Specialized, roundabout production in modern economies implies:  

1. strong interdependence among firms and  
2. financial intermediation embedded in nearly every business.  

### Economics Models as Interpretative Frameworks  

Economic models are best viewed as interpretive frameworks; they do not make falsifiable predictions. Causal density and evolution make model assumptions hard to validate and predictions very context dependent.  

### The Inadequate Metaphor of the Machine  

The predominate view treats the economy as a machine that can be engineered using the mathematics of constrained optimization and the psychology of Behaviorism.  

A better metaphor is a computer network.  

* Characterized by emergent behavior  
* “Software” (i.e., individual and collective knowledge) is at least as important as “hardware”  

### Unemployment as an Adjustment Problem  

Unemployment can be viewed as a combination of static and dynamic adjustment problems.  

* Static: Mismatching and mispricing with a given job structure  
* Dynamic: Entrepreneurs must discover new patterns of specialization and trade by trial and error  

In the PSST framework, the dynamic adjustment problem is the more significant. It is beyond the reach of the metaphor of the machine and has evolutionary characteristics. Permanent job losses are only remedied by discovering new PSST and creating jobs that do not yet exist.  

### Understanding the Subsidize Demand/Restrict Supply Pattern  

The “subsidize demand/restrict supply” prescription for perceived market failures is inconsistent with conventional theories of market failure but common in public policy.  

Specialization implies individual productivity strongly depends on how its combined with other tasks/inputs. Individual well-being is much more greatly affected by the market for what one produces rather than the market for the variety of goods one consumes. Therefore, concentrated interests more naturally form on the supply side of markets.  

Thus, the “subsidize demand/restrict supply” pattern in public policy follows easily from a PSST/public choice framework.  

### Fluctuations as Reputational Minsky Cycles  

Specialized, roundabout production implies that financial intermediation is embedded in nearly all industries/firms. Financial intermediaries also perform risk transformation. To be useful, they are necessarily opaque---reputations must matter in finance.  

Fluctuations can be understood as reputational Minsky cycles of the financial industry.  

1. Hedge Phase: Following downturn, reputations are low. This induces conservative behavior, and reputations begin to improve.  
2. Speculative Phase: Investment increases. More risky but mostly sound projects are financed. Losses can be covered by gains or obscured. Reputations continue to improve.  
3. Ponzie Phase: Reputations are undeservedly high. Increasing levels of investment lead to increasingly unsound projects being financed. Losses accumulate and begin to reach savers. Reputations collapse.  
