---
title: "Reading Notes: 'Models of My Life'"
description: |
  Tags: Herbert Simon, Cognitive Psychology, Biography
author:
  - name: Casey Caprini
date: 02-14-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Book Info

[“Models of My Life”](https://www.amazon.com/Models-My-Life-MIT-Press/dp/026269185X)  
by Herbert A. Simon  

## A Collection of Quotes

### Politics (Loosely)

> “For most of us---those of us who have not won million-dollar lotteries, or suffered sudden crippling accidents---life is much like the chess game. We make hundreds of choices among the alternative paths that lie before us and, as the result of these choices, find ourselves pursuing particular, perhaps highly specialized, careers, married to particular spouses, and living in particular towns. Even if we point to a single event as the “cause” of one of these outcomes, closer scrutiny of the path we have trod would reveal prefatory or preparatory events and choices that made the occurrence of the critical event possible.”  

> “My cosmology shows clearly that the distribution of the world’s goods owes little to virtue and a great deal to the lottery that distributes families, genes, places of birth, material resources, and other forms of access by the throw of cosmic dice. Does that call for a norm of full equality? Only if you believe that people’s aspirations must be guided by comparison with the well-being of others. That belief seems highly unproductive, as it turns the whole of society into a zero-sum game in which some can win only if others lose. There must be better games.”  

> “Acting humanely is an admirable human trait, but it is easy to misconstrue what is at issue. A faculty tenure committee is not determining how many people will be employed in the society, but which people will be employed in a particular university.”  

### Methodology

> “For me, mathematics has always been a language of thought… When I am working on a problem, I am sure that I do not usually think in words, but in terms of a more abstract representation that is perhaps partially pictorial or diagrammatic and partially symbolic. Mathematics---this sort of nonverbal thinking---is my language of discovery. This kind of mathematics is relatively unrigorous, loose, heuristic. Solutions reached with its help have to be checked for correctness. It is physicists’ mathematics or engineers’ mathematics rather than mathematicians’ mathematics.”  

> “The true line is not between “hard” natural science and “soft” social sciences, but between precise science limited to highly abstract and simple phenomena in the laboratory and inexact science and technology dealing with complex problems in the real world.”  

### Rationality

> “What I said and did in the face of concrete situations will convey my beliefs more reliably than could generalities.”  

> “How do people make decisions when the conditions for the economists’ global rationality are not met (or even when they are)?... The central concept is bounded rationality, a label for the computational constraints on human thinking. When people don’t know how to optimize, they may very well be able to satisfice, to find good enough solutions. And good enough solutions can often be found by heuristic search through the maze of possibilities.”  

### Cognitive Psychology

> “Symbols are the stuff of thought, but symbols are patterns of matter. The mind/body problem arises because of the apparent radical incongruity of “ideas”---the material of thought---with the tangible biological substances of the brain. Formal logic… show that ideas, at least some ideas, can be represented by symbols, and that these symbols can be altered in meaningful ways by precisely defined processes.”  

> “Means-ends analysis is accomplished by comparing the problem goal with the present situation, and noticing the differences between them… The observed difference jogs memory for an action that might reduce or eliminate it… The action is taken, a new situation is observed, and, if the goal has still not been reached, the whole process is repeated.”  

> “Experts, human and computer, do much of their problem solving not by searching selectively but simply recognizing the relevant cues in situations similar to those they have experienced before.”  

> “The distinction between the scientific and the professional is largely a distinction between analysis and synthesis. Professionals do not only analyze (understand) situations, they act on them after finding appropriate strategies (synthesis).”  

> “The basic ideas… are that (1) in the course of transforming verbal propositions into images, many things are made explicit that were previously implicit and hidden; and (2) (learned) inference operators facilitate making additional inferences from the images in a computationally efficient way.”  

> “One segment, under the banner “Let language lead the way,” takes verbal reasoning as its metaphor for the problem-solving process, and thinks of reasoning as some kind of theorem-proving structure. The second segment of the cognitive science community uses heuristic search through a problem space (a mental model of the task domain) as its metaphor for problem solving.”  

### Miscellaneous

> “The great enemy of foreign language learning is a sense of shame, an inability or unwillingness to become a child again and let one’s inadequacies show.”  

